name: ci
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build-test-lint-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --locked
      - run: cargo test --locked --all
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo install cargo-deny --locked
      - run: cargo deny check advisories
      - run: cargo deny check bans
      - run: cargo deny check licenses
      - run: cargo deny check sources
