name: ffi
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
concurrency:
  group: ffi-${{ github.ref }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
jobs:
  c_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt-get update && sudo apt-get install -y clang pkg-config
      - run: cargo build --release --locked
      - uses: taiki-e/install-action@v2
        with:
          tool: cbindgen
      - run: cbindgen --output hardlock_snc.h
      - uses: actions/upload-artifact@v4
        with:
          name: ffi-linux-${{ github.run_id }}
          path: |
            target/release/lib*.so
            hardlock_snc.h
  android_jni:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-ndk
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d
      - run: rustup target add aarch64-linux-android
      - run: cargo ndk -t arm64-v8a -o target/android build --release
      - uses: taiki-e/install-action@v2
        with:
          tool: cbindgen
      - run: cbindgen --output hardlock_snc.h
      - uses: actions/upload-artifact@v4
        with:
          name: ffi-android-${{ github.run_id }}
          path: |
            target/android/arm64-v8a/release/lib*.so
            hardlock_snc.h
