name: ffi
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
jobs:
  c_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release --locked
      - name: cbindgen
        uses: taiki-e/install-action@v2
        with:
          tool: cbindgen
      - run: cbindgen --crate hardlock-snc --output hardlock_snc.h
      - uses: actions/upload-artifact@v4
        with:
          name: ffi-linux-${{ github.run_id }}
          path: |
            target/release/libhardlock_snc.so
            hardlock_snc.h
