name: miri
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
concurrency:
  group: miri-${{ github.ref }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
jobs:
  miri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri,rust-src
      - uses: swatinem/rust-cache@v2
      - run: cargo +nightly miri setup
      - run: cargo +nightly miri test --workspace --all-features
