name: release
on:
  push:
    tags:
      - "v*"
jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --locked
      - run: cargo test --locked --all
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo install cargo-deny --locked
      - run: cargo deny check advisories
      - run: cargo deny check bans
      - run: cargo deny check licenses
      - run: cargo deny check sources
      - run: zip -r artifacts.zip README.md README_PERF.md PROTOCOL.md THREATMODEL.md KEY-TRANSPARENCY.md KATS
      - uses: actions/upload-artifact@v4
        with:
          name: hardlock-snc-artifacts
          path: artifacts.zip
